# Generated by Django 5.1.7 on 2025-04-06 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('youremail', models.CharField(max_length=122)),
                ('subject', models.CharField(max_length=122)),
                ('message', models.CharField(max_length=300)),
            ],
        ),
    ]
